services:
  postgres:
    container_name: hiber
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_DB: hiber
      POSTGRES_USER: hiber
      POSTGRES_PASSWORD: hiber
    ports:
      - "5434:5432"
    networks:
      - postgresql
  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
      - redis-data:/data
    command: redis-server /usr/local/etc/redis/redis.conf
    restart: unless-stopped

  elasticsearch:
      image: docker.elastic.co/elasticsearch/elasticsearch:8.15.0
      container_name: demo-elasticsearch
      environment:
        - discovery.type=single-node
        - xpack.security.enabled=false
        - xpack.security.http.ssl.enabled=false
        - ES_JAVA_OPTS=-Xms1g -Xmx1g
      ports:
        - "9200:9200"
      networks:
        - elk

  kibana:
      image: docker.elastic.co/kibana/kibana:8.15.0
      container_name: demo-kibana
      environment:
        - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      ports:
        - "5601:5601"
      depends_on:
        - elasticsearch
      networks:
        - elk

  logstash:
    image: docker.elastic.co/logstash/logstash:8.15.0
    container_name: demo-logstash
    ports:
      - "5001:5001"
    volumes:
      - ./logstash/pipeline:/usr/share/logstash/pipeline
    depends_on:
      - elasticsearch
    networks:
      - elk
networks:
  postgresql:
    driver: bridge
  elk:
    driver: bridge
volumes:
  redis-data:
